# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/test-project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "./package.json" }}
          # fallback to using the latest cache if no exact match is found
           - v1-dependencies-

      - run:
           name: npm install
           command: npm install
      - run:
           name: npm audit
           command: npm audit

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./package.json" }}

      - run:
           name: run tests
           command: npm test

      - run:
           name: node build
           command: npm run build
      - persist_to_workspace: # distを引き継ぐ
          root: .
          paths:
            - dist

  deploy-prod:
     docker:
       - image: circleci/node:10.15
     working_directory: ~/test-project
     steps:
       - checkout
       - attach_workspace:  #引き継いだdistをworking_directoryに配置
          at: ./
       - run:
           name: install firebase-tools
           command: npm install --save-dev firebase-tools
       - run:
           name: Deploy Master to Firebase Prod
           command: ./node_modules/.bin/firebase deploy --only hosting --project "$Firebase_Potal_Project" --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only:
                - master
